name: Run all tests
on: [ push ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      # Rewrite config file to use the correct host.
      # TODO: UGLY HACK
      - run: sed -i 's/localhost:5432/postgres:5432/' autumn-data/src/test/resources/config.hjson
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
      - run: ./mvnw clean test
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

