name: Run all tests
on: [ push ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "15"
      - run: ./mvnw clean test
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TEST_GUILD: ${{ secrets.TEST_GUILD }}
          TEST_CHANNEL: ${{ secrets.TEST_CHANNEL }}
          TEST_GUILD_NAME: ${{ secrets.TEST_GUILD_NAME }}
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      - run: bash <(curl -s https://codecov.io/bash)
