name: Run all tests
on: [ push ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
      - run: ./mvnw clean test
      - run: bash <(curl -s https://codecov.io/bash)
